### ISSUE TITLE
Door Resets

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#10]
While editing a room, I edited the exits for room 11 to to WEST to room 92 and vice versa, with a Door, that is pick/pass'able, but also has a key. (obj 00). This did NOT generate a Door reset. And should. Also, we need to be able to set whether the door resets Open / Closed / Locked.

**Comment by Gwyrdain** [comment]
Door resets must be manually created (in the resets section) at present and contain the open/closed/locked options.  Agree that these should be automatically generated and controlled (and possibly _only_ controlled) from the the associated exits.

**Comment by Gwyrdain** [comment]
Door resets are now controlled at the exit model level.  This means you can assign a door reset type in the exit and door resets will automatically populate.  Door resets are not manually controllable -- but why would they need to be apart from exits.
