### ISSUE TITLE
Auras

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#100]
Mobs don't have the chaotic / lawful / neutral modifiers to their aura flags.

If evil = (Red Aura)
if good = (Blue Aura)

Currently, in the room display and in the line length calculation, it is showing the modifiers:

(White Aura) (Light Red Aura) A ghostly priest chants prayers to a long-dead god. 
(Light Blue Aura) Miriam frantically looks for her brother, Bernard.

**Comment by Gwyrdain** [comment]
Removed the "Light ".

**Comment by TokugawaTFC** [comment]
All prefixes should be included in the line length check for Review.

**Comment by Gwyrdain** [comment]
See Issue #105.
