### ISSUE TITLE
Add links to rooms and mobs and objects edit screen in resets?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#101]
It would be awesome if the Vnum displayed in the reset was an active link that would let you go to edit that particular room or mob or object. 

It would also be awesome if there was a system-provided field in the mob or object editing, maybe under the formatted block, that lets you know where the object or mob is reset, if anywhere.

**Comment by Gwyrdain** [comment]
Added "associated resets" tables to obj and mobs.

Given how cumbersome the general resets table is esp on fleshed out areas, consideration should be given to moving entirely in this direction -- i.e., dealing with resets from the room, obj, mobile level.  R reset is the exception, but this can also be controlled from the room level?

**Comment by Cordir** [comment]
There's a typo in the reset info on the Objects page: "Assocaited Resets" should be "Associated Resets"

**Comment by Gwyrdain** [comment]
Added links to obj and mobile resets.  Need to add to dependent resets.

**Comment by Gwyrdain** [comment]
Dependent resets completed.
