### ISSUE TITLE
Object Summary Page

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#102]
It would be really useful if, on the object summary page, if, instead of Cost, it displayed something about the reset: If it's reset on a mob, have the name of the mob (or "Multiple" if it's on more than 1), if reset in a room, display Room Vnum (Since most room names are kinda long?)

**Comment by Gwyrdain** [comment]
The objects index page?

![image](https://cloud.githubusercontent.com/assets/7820937/14961037/7ee2aed8-104c-11e6-8c03-59a7f44aab26.png)

If so, yeah, I don't care about cost here.  Not sure about reset data in this table.

**Comment by Cordir** [comment]
Yes. That index page.  Or maybe just a numeric value of how many resets there are, if where/who the item is reset in/on is not feasible?

**Comment by Gwyrdain** [comment]
Added the requested column @ objects and mobiles.
