### ISSUE TITLE
Code is not escaping punctuation mobile keyword

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#104]
The keyword for mob 32763 has three question marks in the name. See the attached screenshot.
![keyword-not-escaping](https://cloud.githubusercontent.com/assets/11012495/14973855/3405ca34-10a2-11e6-851d-def0df5edf8b.png)

**Comment by Gwyrdain** [comment]
Since we agreed that only US-ASCII characters are permissible the import function automatically re-encodes the file in that format.  The above was apparently caused by a "smart apostrophe" (like word processors like to use) rather than the plain one:

`’ vs '`

`“ and ” vs "`

**Comment by Gwyrdain** [comment]
I have added specific substitutions to cover these characters: `‘’“”`
If any other special characters appear we'll have to deal with them.
