### ISSUE TITLE
Add missing Object & Mobile Prefixes

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#105]
The following prefixes are in AW now:
**Objects**
```
(Magical)
(Glowing)
(Humming)
(Invis)
```

**Mobiles**
```
(Invis)
(Hide)
(White Aura)
(Blue Aura)
```
Is anything left for objects?  For mobiles, here is what I think is missing:
- [x] faerie fire
- [x] passdoor

What is the text and coloration for these?  Any others?

**Comment by TokugawaTFC** [comment]
Faerie Fire:
(Pink Aura)

Pass Door:
(Translucent) 

I don't think there is any special color. At least there was not for me on the mud. I'll look into the object flags to see if there are any missing.

**Comment by TokugawaTFC** [comment]
For Objects:
Evil was missing: (Red Aura)
Good was missing: (Blue Aura)

**Comment by TokugawaTFC** [comment]
Will the prefixes be pre-pended to the long description and also parsed in the Review? We still have some mobs that have too long a description due to the prefixes.

**Comment by Gwyrdain** [comment]
Added all of the above.  Prefixes appear in the room view of an obj/mob and are accounted for in the review.

**Comment by Gwyrdain** [comment]
See Issue #97 for an additional request for real-time length calcs during editing.  This is coded differently and is a lower priority at the moment.

**Comment by Cordir** [comment]
FYI, the preview isn't showing up in some instances.  Tokugawa uploaded an existing zone, and ran it through the Preview. It's got some long desc length issues, which I was going to fix, but when I go into edit mode on the mob, the preview doesn't happen.

![image](https://cloud.githubusercontent.com/assets/10890489/15294486/0e2d2fe0-1b52-11e6-849f-ae6a3c4a628b.png)

**Comment by Cordir** [comment]
(It IS showing up when I went into an object. Just not on the mob.)

**Comment by Gwyrdain** [comment]
This has been fixed.
