### ISSUE TITLE
Review code is not catching all instances of long description > 80 characters

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#107]
There are five duplicates but I thought I would list them all to be safe.

Room vnum: 32708
(Light Red Aura) Recently risen, a grave-dirt covered ghoul shambles towards you.
81 characters

Room vnum: 32712
(Light Red Aura) Recently risen, a grave-dirt covered ghoul shambles towards you.
81 characters

Room vnum: 32743
(Light Red Aura) Recently risen, a grave-dirt covered ghoul shambles towards you.
81 characters

Room vnum: 32752
(Light Red Aura) Recently risen, a grave-dirt covered ghoul shambles towards you.
81 characters

Room vnum: 32758
(Translucent) (Light Red Aura) Lashing his riding crop, Juan Pablo strides forward.
83 characters

Room vnum: 32761
(Translucent) (Light Red Aura) His gaze promising pain, Carlosanti approaches you.
82 characters

Room vnum: 32768
(Invis) (Translucent) (Light Red Aura) Stilton curses you for disturbing his rest.
82 characters

Room vnum: 32780
(Light Red Aura) (White Aura) Smiling wickedly, Elizabeth gazes at you appraisingly.
84 characters

Room vnum: 32785
(Light Red Aura) Recently risen, a grave-dirt covered ghoul shambles towards you.
81 characters

Room vnum: 32793
(Light Red Aura) (White Aura) A ghostly priest chants prayers to a long-dead god.
81 characters

Room vnum:
(Light Red Aura) (White Aura) The crimson eyes of a vampire meet and hold your gaze.
84 characters

**Comment by Gwyrdain** [comment]
See Issue #100.  Is that wrong?  I can set it back if so.

**Comment by Cordir** [comment]
OK, part of this is totally on me. I would have put money on mobs NOT having the chaos/law/neutrality aspects of alignment : Just (Red Aura) and (Blue Aura). So I asked Gwyrdain to fix that, in a closed item.  SO I was calculating all mine as NOT having that "Light" as part of the aura.

**Comment by Cordir** [comment]
Yes: I was wrong. Please set it back.

**Comment by Gwyrdain** [comment]
Corrected.
