### ISSUE TITLE
Objects in the Page View

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#109]
When you click on a long description for a mob in the Room view, it displays the mob's description and equipment.
When you click on a long description for an object in the Room view, it moves you to the editing screen for that object, rather than showing you details on it (such as contents, if a container). 
It would be helpful if it would display as a mob does - with details, rather than moving screens.

**Comment by Gwyrdain** [comment]
Yes, this is what is contemplated under Issue #15.  It is not clear exactly what should be displayed since objects don't have look_desc's -- maybe "examining" id marked items?  Containers would obviously want to show contents.
