### ISSUE TITLE
Colors on Room Summary

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#110]
![image](https://cloud.githubusercontent.com/assets/10890489/15053407/1f81d3c8-12c8-11e6-8755-6e9dfc140557.png)

The POKE and the information on resets is dark gray on black, which, for those of us with older eyes, is hard to discern. Would it be possible to have a greater contrast color set used?

**Comment by Gwyrdain** [comment]
Adjusted it up a bit.  Where's the happy medium, visible but still fading into the background to be visibly distinct from the "true output?"

**Comment by Cordir** [comment]
That helped :)  Thank you.
