### ISSUE TITLE
The EDIT button

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#112]
Is at the bottom of the page on objects and such.  Could we have a duplicate at the top of the page, so you don't have to scroll all the way down through the big ole page before we can edit it some more? :D

**Comment by Gwyrdain** [comment]
You may have passed by the pencil...  To subtle?
![image](https://cloud.githubusercontent.com/assets/7820937/15063824/4790925c-1302-11e6-87e9-cad613f35542.png)

**Comment by Cordir** [comment]
Ah-HA! er. Yes.  I did.
