### ISSUE TITLE
HOUSTON WE HAVE A PROBLEM

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#113]
![image](https://cloud.githubusercontent.com/assets/10890489/15093870/53b9c47e-1459-11e6-97cc-95ff19e1a89c.png)

book into bookshelf = fine.  What the mob from a completely different zone is doing in here, I have zero idea.

**Comment by Gwyrdain** [comment]
fixed.

**Comment by Gwyrdain** [comment]
You probably want to convert your legacy puts, though.
