### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#114]
Ok, I dunno if this is possible, but..

When I attempted to make an object today, the autocomplete function filled in the text for me. This was drawing the entry from the work of another author.  (I was replicating that item, with their permission) This *could* be used to sneakily see what other people are working on.  Is there a way to restrict autocomplete to only that individual login for the AW?  If not, not a huge deal, but I figured I'd ask.

**Comment by Gwyrdain** [comment]
Can you be more specific? Was it two of your own users? There is no auto
compete in AW so maybe it's browser based?

**Comment by Cordir** [comment]
if there isn't one, then, well, it was some sort of funky browser thingy. Which I've certainly had happen in other instances from time to time.  Please belay this question. :)
