### ISSUE TITLE
Autoflag items with magical applies

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#115]
When someone adds an Applies to an item of any sort, type or kind, please have it auto add the Magic flag. The AWs will rejoice. :D

**Comment by Gwyrdain** [comment]
So how it would work is this... when you add an apply, it adds the magic flag.  However, you can still then go back to the item edit and turn the magic flag off (and the warning would report during a review).  In this way existing, non-magic-flagged items with applies can still be imported with impunity and super-special permission non-magic-flagged items can still be created.  Right?

**Comment by Gwyrdain** [comment]
Erm.  Actually, I looked at it already does this.  Please advise something different is intended.

**Comment by Cordir** [comment]
I guess I hadn't noticed that it was. My bad!
On a *related* note, though - let me know if I should make this its own thing - 
If certain *object* types are selected, a magic flag should be auto-added:
* Scroll
* Staff
* Wand
* Fetish
* Relic
* potion
* pill

**Comment by Gwyrdain** [comment]
Done + type ring (twist) as well.
