### ISSUE TITLE
Resets sub screen

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#116]
I was on the Resets Summary page. I added a reset. This brought me to the sub-reset-page, showing the resets for that mob.  Would it be possible to add a 'Add another Reset' button to that page?

![image](https://cloud.githubusercontent.com/assets/10890489/15258709/b907b792-1912-11e6-927e-de0d3b8b63ce.png)

**Comment by Gwyrdain** [comment]
These items will now appear in the bottom right of the footer.

**Comment by Cordir** [comment]
Yay! Awesomely handy. Thank you. :)
