### ISSUE TITLE
Additional object validations during area review

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#117]
It would be helpful if the below object types could have a warning in the Review section if they have no Value0, Value1, or Value3 assigned to them.

https://wiki.tfcmud.com/index.php/Object_Type_Specifications

- [x] SCROLL
- [x] WAND
- [x] STAFF
- [x] WEAPON
- [x] WEAPON ANIMAL
- [x] FETISH
- [x] ARMOR
- [x] POTION
- [x] ARMOR ANIMAL
- [x] CONTAINER
- [x] DRINK CONTAINER
- [x] FOOD
- [x] MONEY
- [x] FOUNTAIN
- [x] PILL
- [x] RING
- [x] RELIC

**Comment by Cordir** [comment]
I'd disagree with a couple of those:
* Money shouldn't have an apply - it poofs into Gold when you pick it up. This shouldn't be on the review list.
* Armor *can* have an apply, but doesn't have to... This shouldn't be on the review list.
* Armor Animal - same as above - This shouldn't be on the review list.
* Weapon  - same as above - This shouldn't be on the review list.
* Drink Container - I've never seen one with an Apply. Ever. This shouldn't be on the review list.
* Containers - *can* but it's super rare This shouldn't be on the review list.
* Food with an apply is a pill  :D  This shouldn't be on the review list.
* Fountains are required to be a no-take object. They shouldn't have applies. This shouldn't be on the list.

**Comment by TokugawaTFC** [comment]
All of the items here need the review because if they do not have a value
they are not done being written.
On May 15, 2016 8:00 AM, "Cordir" <notifications@github.com> wrote:

I'd disagree with a couple of those:

   - Money shouldn't have an apply - it poofs into Gold when you pick it
   up. This shouldn't be on the review list.
   - Armor *can* have an apply, but doesn't have to... This shouldn't be on
   the review list.
   - Armor Animal - same as above - This shouldn't be on the review list.
   - Weapon - same as above - This shouldn't be on the review list.
   - Drink Container - I've never seen one with an Apply. Ever. This
   shouldn't be on the review list.
   - Containers - *can* but it's super rare This shouldn't be on the review
   list.
   - Food with an apply is a pill :D This shouldn't be on the review list.
   - Fountains are required to be a no-take object. They shouldn't have
   applies. This shouldn't be on the list.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Gwyrdain/apprentices-workshop/issues/117#issuecomment-219290726>

**Comment by Cordir** [comment]
Ok. Your title says "Applies" -- Applies is +1 str, or the like. If you're talking _VALUES_ then yeah, agreed. But Applies, not so much. :)

**Comment by Gwyrdain** [comment]
Renamed and changed the list to a checklist.  I will discretely report the reviews by item here as completed and you can comment on them.

**Comment by Gwyrdain** [comment]
Added v0 warning for SCROLL, WAND, STAFF,FETISH, POTION, PILL, RING, RELIC: No spell level set...

**Comment by Gwyrdain** [comment]
Added v1 warning for SCROLL, POTION, PILL:  No first spell set.

**Comment by Gwyrdain** [comment]
Added v3 warning for WAND, STAFF, FETISH, RING, RELIC: No spell set...

**Comment by Gwyrdain** [comment]
Added v1 warning for WAND, STAFF, FETISH, RING, RELIC: Max charges for <obj> should be > 0...

**Comment by Gwyrdain** [comment]
Added v1 and v2 warnings for WEAPON and WEAPON ANIMAL:  Max damage should be >0, Min damage should be >0...

**Comment by Gwyrdain** [comment]
Skipping fountain: A 0 0 0 0 fountain should actually be the most common: water with no spell

**Comment by Gwyrdain** [comment]
Add v0 warnings for FOOD (and PET FOOD): Hrs of nourishment should be >0.

**Comment by Gwyrdain** [comment]
Added v0 warning for MONEY:  should be worth >0 gold.

**Comment by Gwyrdain** [comment]
Added v0 and v1 warnings for ARMOR and ANIMAL ARMOR:  AC should be >0... Max AC should be >0...

**Comment by Gwyrdain** [comment]
Added v0 warning for CONTAINER:  Should have a hold weight >0...

**Comment by Gwyrdain** [comment]
Added v0 and v1 warning for DRINK CONTAINER:  Should have >0 drinks.  Should have >0 drinks left.

**Comment by Gwyrdain** [comment]
All items are done to the best of my understanding.  Please review and advise if anything is missing or wrong.

**Comment by TokugawaTFC** [comment]
This looks good. Thanks for adding this.
