### ISSUE TITLE
Error when accessing objects

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#120]
I was attempting to work with some objects today, and have gotten this message a couple times:

NoMethodError in Objs#index
Showing /app/app/views/objs/index.html.erb where line #48 raised:

undefined method `formal_vnum' for "UNKNOWN":String
Extracted source (around line #48):
45
46
47
48
49
50
51
          
                         <% target_reset = @area.resets.where(:reset_type => ['O', 'P', 'I'], :val_2 => obj.id).first %>
                         <% if target_reset.reset_type == 'O' %>
                           <% target = room_info(target_reset.val_4,'self') %>
                           <%= link_to "At #{target.formal_vnum}", area_reset_path(@area, target_reset) %>
                         <% end %>
                         <% if target_reset.reset_type == 'P' || target_reset.reset_type == 'I' %>
                           <% parent = target_reset.parent %>

Rails.root: /app

Application Trace | Framework Trace | Full Trace
app/views/objs/index.html.erb:48:in `block (2 levels) in _app_views_objs_index_html_erb__3412285684690635816_70210918777680'
app/views/objs/index.html.erb:29:in `block in _app_views_objs_index_html_erb__3412285684690635816_70210918777680'
app/views/objs/index.html.erb:2:in `_app_views_objs_index_html_erb__3412285684690635816_70210918777680'
Request

Parameters:

{"area_id"=>"56"}
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by Gwyrdain** [comment]
For some reason the room in question was not found?  I did a quick patch so it just says "UNKNOWN" in this case, but this doesn't answer the why the room wasn't found.  Additionally, it's not clear that the associated reset is working properly?

I assume this is related to an imported area as recently referenced in Issue #105.  These imports still need to be reviewed for oddities that I haven't considered.  For example it is always good to make sure the # of objs, rooms, mobs, resets (by type) match your expectations.  Another good test is to import then immediately export and do a text compare -- some differences are expected just based on AW formatting (of resets for example, or by use of the v2 header), but other differences may be helpful.

**Comment by Cordir** [comment]
This was *not* in an Imported zone, but rather a zone I've been working on for some time.

**Comment by Gwyrdain** [comment]
In that case the patch should be good and if you get an unknown it probably means that some related item got deleted along the way (like a parent reset, room or mob)

**Comment by Gwyrdain** [comment]
Er, no.  There was a problem -- found and fixed.
