### ISSUE TITLE
Download / Upload issue? Flag translation?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#121]
Boneyard was created in the Workshop. It was downloaded and then uploaded. I have both versions.
I'm not sure what happened, but this:
[32780] [DARK NO_MOB FLY_OK] <INSIDE> {no room special +}

turned into this:
[32780] [NO_MOB   ] [DARK     ] **[GUILD    ]** [FLY      ] [NO VNUM  ]  <inside>

(The Novnum part is fine - tynian has auto-added that to all new zones for the first 6 months post install)  But the Guild part is a bit .. weird.

**Comment by Gwyrdain** [comment]
Can you share just the raw room record from the imported file?

**Comment by Gwyrdain** [comment]
Er, wait.  Is that second entry the actual TFC view?

**Comment by Cordir** [comment]
Yes - that's the live mud view.

**Comment by Cordir** [comment]
In the AW, it doesn't appear on the list of flags in either the original or uploaded version
but when it was loaded live, the Guild flag appeared mystically.

**Comment by Cordir** [comment]
Here's the UPLOADED version:
![image](https://cloud.githubusercontent.com/assets/10890489/15337324/c9db30e0-1c40-11e6-90d1-1562072b743c.png)


#32780
In the Crypt of Familia Von Harovich~
This elaborate stone vault has an arched roof supported by four Ionic
columns. The spiral staircase that winds upward mirrors their graceful
shape. The masonry-work is of the highest quality, with marble imported
from the southern continent. Blackened metal sconces hang upon the walls,
unlit torches filling them.  The only non-architectural ornamentation here
are large mirrors of silver, carefully hung to reflect the image of the
casket that lays upon a central bier. To the south, a heavy iron door,
twisted and nearly broken, blocks the way. A scattering of destroyed
masonry reveals that something exited that chamber with great violence.
~
327 1048597 0

**Comment by Gwyrdain** [comment]
It appears that the 2^4 bit (16) is set...

Should that be 2^3 (8) = indoors instead?

**Comment by Cordir** [comment]
In the Original version, yes, it was set to INDOORS:
![image](https://cloud.githubusercontent.com/assets/10890489/15339194/db5ec57c-1c48-11e6-85b2-c3c4f9065302.png)


#27380
In the Crypt of Familia Von Harovitch~
This elaborate stone vault has an arched roof supported by four Ionic columns.
The spiral staircase that winds upward mirrors their graceful shape. The
masonry-work is of the highest quality, with marble imported from the southern
continent. Blackened metal sconces hang upon the walls, unlit torches filling
them.  The only non-architectural ornamentation here are large mirrors of
silver, carefully hung to reflect the image of the casket that lays upon a
central bier. To the south, a heavy iron door, twisted and nearly broken, blocks
the way. A scattering of destroyed masonry reveals that something exited that
chamber with great violence.
~
**273 1048589 0**

**Comment by Gwyrdain** [comment]
I am not able to recreate this problem on my own.  Maybe @TokugawaTFC can check the raw file that was later imported?

**Comment by TokugawaTFC** [comment]
The room record is below. The room flags here and on the mud match.

#32780
In the Crypt of Familia Von Harovich~
This elaborate stone vault has an arched roof supported by four Ionic
columns. The spiral staircase that winds upward mirrors their graceful
shape. The masonry-work is of the highest quality, with marble imported
from the southern continent. Blackened metal sconces hang upon the walls,
unlit torches filling them.  The only non-architectural ornamentation here
are large mirrors of silver, carefully hung to reflect the image of the
casket that lays upon a central bier. To the south, a heavy iron door,
twisted and nearly broken, blocks the way. A scattering of destroyed
masonry reveals that something exited that chamber with great violence.
~
327 1048597 0
D2
~
~
2 32752 32797
O
crypt~
D4
~
~
0 0 32777
E
masonry~
New brick, only a few decades old, was used in an attempt to further
bar the door to the south. Something smashed through it, from the other
side, with overwhelming and horrific force, turning the bricks to scattered
chunks of rubble.
~
S

**Comment by Gwyrdain** [comment]
If the raw file you imported has room flags as "1048597" then the "GUILD" bit was set prior to upload.  For now, I have added the guild room flag so that it can be unset in that area easily.  I will be looking at a way to report/warn on unknown flags being set.

**Comment by Gwyrdain** [comment]
"UNKNOWN_FLAG(S)" will now appear in rooms where such is the case -- perhaps whatever 2^8 or 2^12 is/was.
