### ISSUE TITLE
Deleting a duplicated reset

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#123]
I was looking for the 'duplicate this object' button (we have one for mobs, and I thought one was made for objects, too) and hit the "duplicate this reset" instead. It brought me to the reset summary, and yep, there was a duplicate reset of that object in that room.  

![image](https://cloud.githubusercontent.com/assets/10890489/15411783/039bd106-1de8-11e6-906c-65d060514281.png)

I hit the Delete button to remove the extra reset, and got an error:

ActiveRecord::RecordNotFound in ResetsController#show
Couldn't find Reset with 'id'=1277

Extracted source (around line #176):
174
175
176
177
178
179
          
  private
    def set_reset
      @reset = Reset.find(params[:id])
    end

    def set_area

Rails.root: /app

Application Trace | Framework Trace | Full Trace
app/controllers/resets_controller.rb:176:in `set_reset'
Request

Parameters:

{"area_id"=>"35",
 "id"=>"1277"}
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by Cordir** [comment]
(When I refreshed the page in my browser, the reset was gone.)

**Comment by Gwyrdain** [comment]
It was trying to return to the deleted reset, should be fixed now.
