### ISSUE TITLE
Copy Object

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#124]
If we don't currently have a Copy Object function, as we do for copying mobs, could we have one? :D

**Comment by Gwyrdain** [comment]
The copy object function was added.

**Comment by Cordir** [comment]
Could you add it to the individual object screen as well as the object summary?

**Comment by Cordir** [comment]
FYI, when you COPY an object, it does not retain the object worn slot. That field is blanked out.
