### ISSUE TITLE
Drink Containers disallowed from being HOLD

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#125]
I attempted to equip a mob with a held drink container and got an error. I don't *think* there's any regulation against it...

![image](https://cloud.githubusercontent.com/assets/10890489/15412707/47ff8ad4-1def-11e6-88eb-18d45d54d1dd.png)

**Comment by Gwyrdain** [comment]
Is the object's wear flag set to hold?

**Comment by Gwyrdain** [comment]
Works for me.  See here:
https://apprentices-workshop.herokuapp.com/areas/43/rooms/2093
