### ISSUE TITLE
Add mismatched exit type to review section

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#126]
There is a door in The Bonyard v2 (room vnum 32700) which has a door going south, The room directly south (room vnum 32703) has no doing going north. It would be useful to a warning in the review so this can be caught before the area is put on the test port.

**Comment by Cordir** [comment]
I'm not sure what you're referencing:
32703 has an exit SOUTH to room 32774. 
![image](https://cloud.githubusercontent.com/assets/10890489/15451806/67bec30a-1f9b-11e6-99e6-6428d89418f3.png)

Room 32774 has an exit NORTH to room 32703. 
![image](https://cloud.githubusercontent.com/assets/10890489/15451809/741afc5e-1f9b-11e6-8bb1-50bd03b5dca3.png)
There is no mis-match.

Now, did you maybe mean the exit going NORTH out of 32703, which is an -out-of-zone exit?

**Comment by TokugawaTFC** [comment]
32700 has an exit and door going south.
32703 which has an exit going north back to 32700 does not have a door. it only has an exit. If you open the room 32700 in the editor and edit the room. When you mouse over the south exit over the icon to the right of the "exit to" section you see the following text: "mismatched exit types: Door (pick/pass ok) vs No door"

**Comment by Cordir** [comment]
OK, that makes much more sense than your original post. :)

**Comment by TokugawaTFC** [comment]
Ooops. I typod the room name in the first post. No wonder you were confused. ;)

**Comment by Cordir** [comment]
(it's also very late *and* I am generally easily confused ;D )

**Comment by Gwyrdain** [comment]
Not sure what's going on here.  This check already exists, but seems to not be reporting in some cases.

You can see an example in the practice fields, but only one side of the mismatch is reporting (whereas both should be).  https://apprentices-workshop.herokuapp.com/areas/43?review=true

Also, while looking at this I noticed that mismatch does not check that keys are set identically (i.e., same key required for both sides), but it probably should.

**Comment by Gwyrdain** [comment]
Area Review fixed now, though I haven't added the key checking to the mismatched doors logic.

**Comment by Gwyrdain** [comment]
Key checking is added.
