### ISSUE TITLE
Text fields should word wrap 

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#13]
Automatically word wrap room, mob, and extra descriptions so that the lines are <= 77 characters.

**Comment by Gwyrdain** [comment]
This should be working.  Let me know if you see any that I forgot.  Wiki states 75 in a number of instances so I was going with that to date.  I can easily bump it up, but maybe update wiki too?

**Comment by TokugawaTFC** [comment]
Hm, not sure which is right then. I got this from an old document that was being used for another attempt at a new editor.

**Comment by TokugawaTFC** [comment]
I'm looking at a room description right now and it's not wrapping until about 110 characters.

**Comment by Gwyrdain** [comment]
I will update to a global variable of some type and then it can be changed again whenever.

**Comment by Gwyrdain** [comment]
It only wraps when it outputs.  See the formatted block/record for that item.

**Comment by TokugawaTFC** [comment]
would it be possible to wrap it in the editor? Otherwise you will not be able to tell what it looks like until you scroll down to the Formatted Rooms block. I could see this getting very frustrating as you would have to scroll down a lot to see how it's formatted, then scroll back up, change it, then scroll back down, etc.

Or make a formatted rooms block below the room itself. So when you click the Update button for the room, mob, object you can see the item you are working on.

**Comment by Gwyrdain** [comment]
I honestly don't know.  I would think that the author shouldn't be so nit picky and just let the software word wrap for you just like we do in real life with Word, etc.  The user always has the option to manually add linefeeds if they're named Bethany.  I will flag for enhancement, but ... hrmm.

**Comment by Cordir** [comment]
: P

Just because of you and your "let me control your word wrapping" I *did not* make the suggestion that the initial text window be courier, so that I could eyeball line/break how I want... (but I still have Notepad!)

**Comment by Gwyrdain** [comment]
All of those text fields should be monospace typeface (though courier is normally the last choice).  Are yours not showing as monospace?

**Comment by Gwyrdain** [comment]
It's kind of ug, but I guess you could place a ruler above the text area...  Even if it weren't ug, I don't like that it implies that you <b>should</b> control your own linefeeds.

![image](https://cloud.githubusercontent.com/assets/7820937/6203842/d2327142-b4f2-11e4-9f2c-ddeaa7b3b71e.png)

**Comment by Gwyrdain** [comment]
Ok.  I added a "use rulers" option to areas.  That way you can if you must.

![image](https://cloud.githubusercontent.com/assets/7820937/6204101/56cddf9c-b4fb-11e4-89ff-06edc0e7d296.png)

**Comment by Cordir** [comment]
I must, I must. :D

**Comment by Cordir** [comment]
![image](https://cloud.githubusercontent.com/assets/10890489/6223397/c5252d6e-b62d-11e4-9b06-c62c06448a7b.png)

**Comment by Gwyrdain** [comment]
Ha ha.  Sorry... you have to "Edit" the area to change its settings.

**Comment by Cordir** [comment]
Danke.
