### ISSUE TITLE
Password reset function errors

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#130]
I got a report from a user that the password reset function does not work. I tried it myself and below is the error I see.
![screenshot at 2016-05-30 09-29-37](https://cloud.githubusercontent.com/assets/11012495/15654497/a8265ea8-2649-11e6-8381-9c6c16776291.png)

**Comment by lpkirby** [comment]
Based on the error message, the code is looking for an smtp server on localhost and it isn't there.

@Gwyrdain  - Does this server allow sending of email?  If so, do you know the setup for it?

**Comment by Gwyrdain** [comment]
https://elements.heroku.com/addons/#email-sms

**Comment by lpkirby** [comment]
Looks like the SparkPost addon will do smtp and it's free if we send 100,000 emails per month or less.

https://elements.heroku.com/addons/sparkpost

So as long as @TokugawaTFC doesn't get way too password reset happy, this should be more than enough.  :)

**Comment by Gwyrdain** [comment]
Sparkpost didn't work since I couldn't verify my sending domain.  Sendgrid worked, though.  Only 12k emails free, but I'll take my chances.
