### ISSUE TITLE
Reciprocality doesn't 'stick' when adding a directional look description

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#139]
I made a room, with four reciprocal exits.
I then went back into the exit, to add a Look description for that direction/exit.
The exit lost the checkmark in the Reciprocality box, and an error appeared in the exit list for the room.

![image](https://cloud.githubusercontent.com/assets/10890489/15947004/eeaca5b8-2e5e-11e6-9453-e845dc736aa7.png)

**Comment by Cordir** [comment]
Did you have a question about this? You flagged it...?

**Comment by Gwyrdain** [comment]
What's the status on this?  I can't tell from the image what the triangle is reporting.  I can't reproduce and it seems like your error went away?

**Comment by Cordir** [comment]
Ok. I thought this was still an issue, but I just tested it, and it doesn't appear to be the case any more. *scratches head*
