### ISSUE TITLE
Disallow the use of the tilde in descriptions

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#142]
The tilde ~ causes the mud to go bonkers.  Could the AW scold folks soundly when they try to use it, and put up a warning saying its a disallowed character?

**Comment by tyn-** [comment]
Or maybe a small electric shock.

**Comment by Cordir** [comment]
*yelps*

**Comment by Gwyrdain** [comment]
Now disallowed.

Where previously allowed chars were limited to regex `/[\x0A\x0D -~]/`, now limited to `/[\x0A\x0D -}]/`.
