### ISSUE TITLE
Spec_mage_protector

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#143]
We have this as a selectable item, but it has a variable string option that the Workshop doesn't offer:

https://wiki.tfcmud.com/index.php/Spec_mage_protector

(The specific string of the message can be set, which I would like to do.. :D )

**Comment by Gwyrdain** [comment]
You need to create a string entry first, then it will be available to select under the message drop down list for your spec_mage_protector entry.

![screenshot 2016-08-24 at 9 26 11 pm](https://cloud.githubusercontent.com/assets/7820937/17956816/6f6d9fe0-6a41-11e6-9193-7e2e8227c408.png)
