### ISSUE TITLE
Add ability for walk through mode

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#15]
Have the ability to walk-through the zone and have limited interaction with the rooms, mobs and objects.
Be able to see in containers to verify resets were done correctly.
Look at mobs and see the equipment worn and in inventory.
Be able to list items for sale on a vendor.
Get a notice in walk through mode when you walk through a door that is closed and or locked or needs pass-door to pass through it.

Poke a mob in walk-through mode. An example of how the Muditor does this is below. We may want to add more information if there is something else here that is not listed that might be helpful to know.
 
You poke him in the ribs.
 
A minotaur applicant says 'Hello, let me tell you about myself'.
 
A minotaur applicant says 'I'm level 22, and my alignment is 0'.
A minotaur applicant says 'My action flags are Scavenger, and Stay Area'.
A minotaur applicant says 'My affect flags are... oh, I don't have any of those.
 *sniff*'.
A minotaur applicant says 'I'm not an animal, and I can wear equipment'.
A minotaur applicant says (in Minotaur) 'My known languages are Minotaur, and Thoras'.

**Comment by Cordir** [comment]
well, hell. I"ve been using the damned thing for 15+ years and I had no idea you could do that in walkthrough mode with mobs.

**Comment by Gwyrdain** [comment]
Started something headed in this direction.  Rather than form view for rooms, trying more of a 'mud view' with appropriate linked exits.  In theory you can now "walk through" rooms with a little clicking.  Mobs, objs are not shown... (yet?).

**Comment by Gwyrdain** [comment]
In this view, though, are the room vnum, room flags, and terrain supposed to be certain colors?

**Comment by TokugawaTFC** [comment]
On my computer using Mudlet the room name is green and the room flags are white.

**Comment by Gwyrdain** [comment]
Here's what I get w/o the god-ish stuff (example from mudlet too in this case).
![image](https://cloud.githubusercontent.com/assets/7820937/6316534/f8521db6-b9e6-11e4-9232-276f9c744a38.png)

**Comment by Gwyrdain** [comment]
I'm flip flopping (here too) in favor of we simpletons who are used to seeing room name proceeded by exits without extra muck...  Pushing the supplemental data above in stead.
![image](https://cloud.githubusercontent.com/assets/7820937/6316587/f4f10a68-b9e8-11e4-9a1b-ee5c19448f1e.png)

**Comment by Cordir** [comment]
I think that view makes sense.

**Comment by Gwyrdain** [comment]
If anyone is bored and wants to document the various prefixes to mobs and objs in room view, that would be helpful as a checklist.  Also note if the prefix has an associated color.  For example:

Mobiles
"(White Aura)" / Sanctuary / White
"(Light Blue Aura)" / Good / white paren, blue text
"(Light Red Aura)" / Evil / white paren, red text

Objects
"(Humming)" / Humming / none
"(Glowing)" / Glowing/ none

etc.
Also, what is their order?
For magical, what is the exact calc on the different grades?

**Comment by Gwyrdain** [comment]
Using these color names for the "standard" ansi 16.
![image](https://cloud.githubusercontent.com/assets/7820937/6322063/fa33e02c-bac9-11e4-871a-456214694697.png)

**Comment by Gwyrdain** [comment]
I have added some things, but not all.  Also, added rulers to this view -- not sure about that.
![image](https://cloud.githubusercontent.com/assets/7820937/6322082/693f3bce-baca-11e4-92ed-10c404b5ad33.png)

**Comment by Gwyrdain** [comment]
Numerous improvements were made (see Issue #34).  With the following items this issue can be closed, I think:
*Add something equivalent to the poke referenced above.
*Add looking in containers (with nesting).
*Add the put/insert (with nesting) in-line actions similar to the give | equip.

**Comment by Gwyrdain** [comment]
Added "poke."

**Comment by Cordir** [comment]
A grand library patron says 'I'm level 45, and my alignment is 0'.
A grand library patron says 'My act flags are Sentinel and Stay Area'.
A grand library patron says 'My affect flags are Detect Evil, Detect Magic, and Detect Good(-TDB-)'.
A grand library patron says 'I'm not an animal, and I can wear equipment'.
A grand library patron says (in none) 'My known languages include none'.

What does -TDB-  mean in the above example?

**Comment by Cordir** [comment]
Also, is it possible to request word wrapping?

![image](https://cloud.githubusercontent.com/assets/10890489/15053371/ea980876-12c7-11e6-8ccb-41ce9a620f32.png)

**Comment by Gwyrdain** [comment]
fixed these two items.

**Comment by Gwyrdain** [comment]
Studying objects and viewing container contents with associated p/i resets.  This closes the basic roadmap for this issue.  Please make new requests separately.
