### ISSUE TITLE
Wrong Spell #... item of Naturalize becomes.. Meteor Swarm!

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#150]
I created an object on the AW and selected Naturalize as the spell. When I load the object on the mud and ostat it, it is Meteor Swarm. 

 > slookup naturalize
Sn:   89 Slot:  159 Skill/spell: 'naturalize'

Invis 73  1000ma(1000) 11067128gp NH HL > slookup meteor swarm
Sn:   85 Slot:   95 Skill/spell: 'meteor swarm'

#32813
pamphlet leaves~
a pamphlet of sewn leaves~
This small pamphlet was made by sewing leaves together.~
~
2 0 16385
10 95 0 0
1 0 0

Mebbe a typo on the back end?

**Comment by lpkirby** [comment]
Looks like the original typo was in the wiki.  I just checked and it says both naturalize and meteor swarm are 95.

I'll have the code fixed shortly.  I'm not sure I have a wiki account.  Would you mind fixing it in the wiki?
