### ISSUE TITLE
Object Wear Flag typo?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#155]
so the wiki  ( https://wiki.tfcmud.com/index.php/Object_Wear_Flags ) shows that the object wear flag for HELD is 16384.  Objects created in the AW are showing as 16385 when 'hold' is selected.

This did not use to be the case.  

Based on a zone download I did on 07-01-16, at that point, the object wear flag for HOLD was 16384. So some sort of change occurred between then and the next time I saved a local copy, which was 07-05-16.

**Comment by TokugawaTFC** [comment]
This is 16385 because it also has to have a take flag. If that flag was missing no one would be able to pick up the item.

**Comment by TokugawaTFC** [comment]
Hm, I re-read your post and I don't know why it would have changed. The value has to be be 16385 for the item to be picked up however.

**Comment by Cordir** [comment]
oh. well. shit. here I thought I'd figured out the problem. :(
