### ISSUE TITLE
Add ability for a nested give reset to a mob

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#16]
*Give container to mob, which has a container with items inside.
M 0 2109 1 1297                  Minotaur Key Holder
E 1 2161 20 1 7                  Huge Spiked Seste
G 1 2129 100                     a chest
I 0 2162 1 2129                  Multi-Colored Key Ring (contains color key)
P 1 2153 100 2162                Red Key
P 1 2154 100 2162                Black Key
P 1 2155 100 2162                White Key
P 1 2156 100 2162                Brown Key
P 1 2157 100 2162                Yellow Key
P 1 2158 100 2162                Maroon Key
P 1 2159 100 2162                Green Key
P 1 2160 100 2162                Grey Key
E 1 2161 100 16                  Huge Maul

**Comment by Gwyrdain** [comment]
What is an "I" reset?  This is not documented on wiki.

**Comment by TokugawaTFC** [comment]
Yeah, I did not know about this reset either until I found it in another area. In general it allows you to put a container in a container. the second container having items inside it. I'll ask Tynian about it if you need more details as that's all I have.

In the example above the mob is carrying the chest, and inside the chest is the key ring which is also a container. In the key ring are items as well.

**Comment by Gwyrdain** [comment]
Will reopen Issue #71 and assume both Issue #16 and Issue #17 under the one heading.
