### ISSUE TITLE
Add ability to support all the Area Special Functions

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#18]
This can be added later as it will be a lot of work but it would be nice to support this eventually. 

Please see this link for the Special Functions.
http://wiki.tfcmud.com/index.php/Area_Special_Functions

**Comment by Gwyrdain** [comment]
All specs should be in.  The only caveat is that most extended spec funs are only in generically and still need to be prettified and have validations added on an individual basis.

**Comment by Gwyrdain** [comment]
These items should be reviewed but, all extended specials and the one extended room special are done.  Still need to do extended triggers.

**Comment by Gwyrdain** [comment]
trig_time_block in too.  just two to go, but they use bitwise flags in an extended value slot (argh!)

**Comment by Gwyrdain** [comment]
remaining triggers complete.
