### ISSUE TITLE
Add (room/object/mobile)

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#2]
Adding a link at the TOP of the page would be handy, so one does not have to scroll all the way through the list to get to the 'let's do that again' link.

**Comment by Gwyrdain** [comment]
Added this "+" as a quick add link to rooms, mobs, objs, helps, strings.  Other elements are dependent and can only be added from the relevant record (i.e., only a room can get a room special function).

![image](https://cloud.githubusercontent.com/assets/7820937/6090604/46c9c6b2-ae3c-11e4-8f98-b8271bb76c44.png)
