### ISSUE TITLE
Request from Tamar - Lock areas to Area Coordinator edit only

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#20]
I would like to be able to lock an area from further modifications by the author (so only area coordinators can make edits after an author says that are done)

This way we can make edits without having to review the whole file again.

**Comment by Cordir** [comment]
Perhaps a 'status' field ? 
That when the author changes the status to 'submitted' it's in the AC's hands?  And if needed, the AC's can revert control back, if they have major changes they want the author to do?  (I don't much like the idea of the AC's being able to throw a switch that removes author control without some action having been initiated by the author.)

**Comment by Gwyrdain** [comment]
Understood.  Passing control from author to AC (and back if needed) seems right and in any case simulates the current process which I assume involves passing files back and forth and in which only one party has de facto "edit" control at a time.

**Comment by Gwyrdain** [comment]
The requested control functionality has been accommodated the addition of ownership transfer.  At this time the "shares" are not affected (i.e., they are not purged on transfer).  If you expect to be able to see the area after a transfer, add yourself as a share before transfer.

![image](https://cloud.githubusercontent.com/assets/7820937/14411567/e3b89c1c-ff00-11e5-83c3-c4afa49bd36b.png)
