### ISSUE TITLE
Request from Tamar - Save previous versions when importing area file.

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#21]
I would like to be able to export the area, make edits outside of it, and then upload the revised version. In this case I'd like the previous versions to remain behind just in case.

**Comment by Gwyrdain** [comment]
This is fine generally and import function is in-progress (but a bear so the timeline in indeterminate and probably ranks below some of the other functionality).  Import would definitely create a new instance and some thought will need to be given regarding how to distinguish (maybe just manual versioning).

That said, if there are functional reasons why you would want to edit outside, I would like to hear them and improve the editor so you wouldn't "want to" if that makes sense?

**Comment by TokugawaTFC** [comment]
Here's Tamar's response: "One of the reasons I don't use the current
muditor to do my portion of the area coord stuff is that I review it for
content, typos, and grammar. To do that in the current muditor (and from
what I can tell in this one) requires opening each room, mob, and object
individually and then from there also going into all of the directions and
extra descriptions. It's much easier to see them all laid out in one long
form without all the extra clicks. So I would like to be able to do that.
If there's a better/easier way that would work too."

**Comment by Gwyrdain** [comment]
Awesome. I'm sure we can come up with something (at some point).  This is likely easier than finishing import... but more to come.

**Comment by Gwyrdain** [comment]
Closing in favor of Issue #65.  Will add versioning to the roadmap.  Be sure you're subscribed to notifications on #65.
