### ISSUE TITLE
Room creation at the exit level?

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#24]
From user stories:
- I need an editor that creates reciprocal exits.
- I need to be able to create an exit link to a room that hasn't been created yet.

These can probably both be addressed by a button push that creates an exit, a destination room and the reciprocal exit in one click (similar to how an look-only exit is created currently)

**Comment by tyn-** [comment]
I concur that this would be nice.  I'd hoped that it would just work when I tried it.

**Comment by Gwyrdain** [comment]
Added.  So long as an additional room vnum is available, a new "empty room," and reciprocal exit (both sides) will be created.
