### ISSUE TITLE
Blank.ARE

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#27]
Button to generate 100 rooms / mobs / objects as a starting template.

**Comment by TokugawaTFC** [comment]
Nice feature. Would make it much quicker to actually get writing.

**Comment by Gwyrdain** [comment]
Pre-create rooms avail for rooms (button at bottom of rooms index).  it fills up all remaining vnums.

**Comment by Cordir** [comment]
*squee*!

**Comment by Gwyrdain** [comment]
For mobs and objs a button to add 10 at a time is in.  Maybe this could be a field... but this was quick and easy.
