### ISSUE TITLE
In Resets... (need to Give, Equip, Put from within Reset)

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#28]
Allow writer to (also) add Give and Equip resets while in the original reset creation, rather than having to exit out to the Resets list and add them there.

**Comment by Cordir** [comment]
Also, "COPY" object resets to a new MOB would also be nifty. (Ie, 30 guards wearing the same combo of 4 items - would be nice to copy, rather than redo each time.)

**Comment by Gwyrdain** [comment]
I dropped the sub-reset table view into the reset view, so that should help?  Close if this is ok for now.
![image](https://cloud.githubusercontent.com/assets/7820937/6342396/777454b0-bb95-11e4-8596-12f6b367201b.png)

**Comment by Gwyrdain** [comment]
an inline give/equip would be better...
