### ISSUE TITLE
Area no long accessible

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#29]
I was working on an area for this weekend's quest.  Unfortunately, I just started getting a "The page you were looking for doesn't exist" error for no apparent reason.

The "My Areas" section shows my area, including mobiles, objects, and rooms counts, but selecting the area results in the above error.

**Comment by Gwyrdain** [comment]
Something goofy on show area page.  Will look into it.  In the mean time you can bypass by going to /rooms /objs or /mobiles.

**Comment by Gwyrdain** [comment]
Something buggy in the 'area review' section.  Temporarily removed.

**Comment by Gwyrdain** [comment]
Area review moved to a discrete button and separate page.  Bug not found yet, but this allows use of review in the mean time for areas that don't encounter the problem.

**Comment by Gwyrdain** [comment]
The is_reciprocal? method was lacking a check on whether the opposite end exists (within the area).  Should be fixed.  Please check your "Review Area" button and report problems or nonsense warnings!
