### ISSUE TITLE
Show room title when editing an exit

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#30]
So, if I were properly writing an area, I'd have a map, and I could match the vnum with the room number.  But I'm not.  It would be nice if the exit edit screen shows the title of the room that the exit refers to, so I have context.

**Comment by Gwyrdain** [comment]
Of course.  Done.  So many little things I have forgotten.  Keep these easy ones coming.

**Comment by tyn-** [comment]
Thanks!
