### ISSUE TITLE
Highlight current room when editing room exits

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#32]
This editor is really pretty slick.  Nice!

It would be nice when looking at the room list in the edit exit view if the current room is highlighted on the list.  Exits that refer back to the same room is uncommon, so doing so should stand out.

**Comment by Gwyrdain** [comment]
I don't know that I have control of what's actually in the selection list (drop down)?  Are you just looking for a visual que that you're doing something uncommon.  Maybe some bit turns warning orange?

**Comment by tyn-** [comment]
Anything that would help inform you that you are self-referring an exit back to the same room would be helpful.

**Comment by Gwyrdain** [comment]
Normal:
![image](https://cloud.githubusercontent.com/assets/7820937/6312798/aac14542-b944-11e4-8c5f-a8c8f9891914.png)
Loopback:
![image](https://cloud.githubusercontent.com/assets/7820937/6312800/b707542c-b944-11e4-8877-a2d27c9be1e4.png)
