### ISSUE TITLE
"Next"

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#33]
When working on a room or object or mob, having a button that would allow you to go to the next existing record of that type would be nifty rather than exiting that item, going back to the main list, scrolling down, finding the one you need after a scrolling past it, clicking on it...

**Comment by Gwyrdain** [comment]
Added this for rooms, obj, mobs.  Functional, but not sure this is the final word visually. 
![image](https://cloud.githubusercontent.com/assets/7820937/6314951/319a6732-b9af-11e4-9be7-0d70820ec54c.png)
