### ISSUE TITLE
Asking the Impossible?

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#34]
A properly planned area is structured so that it's straightforward to create all of the rooms at once, and then objects, etc., and finally put all the resets together.

On the other hand, what I'm writing for the quest I'm working on is not a properly planned area.  I find myself having some difficulties.  I admit that's my own fault.

Would it be possible to access the various sections from within one another?

For example, I create a room.  I know that I want a mob in that room.  From the room screen, I'd like to be able to add (or create) the mob that goes into that room.  Thus, both the mob and the reset would be taken care of as a result of me being in the room view.

Objects would be the same way.  Within the room, I could add or create an object that goes into the room.

It could be the same way for mobs.  Once the mob is created, I could select a room (or rooms) that the mob should go in, or I could select an object (or objects) that should be popped on the mob.

This makes creating mobs, objects and rooms and the associated resets more transparent.

Does what I'm outlining make sense?  Too "pie in the sky?"

**Comment by Gwyrdain** [comment]
I agree and this is more in line with how I think I would go about area
design, ceteris paribus.  I had in mind something of this sort already. The
technicals should not be problematic, just need to think through design
considerations.  Additional input likely required.

**Comment by Gwyrdain** [comment]
Some initial steps down this road... far from the end of the journey.

![image](https://cloud.githubusercontent.com/assets/7820937/6323762/0ddda144-baed-11e4-8464-9c10975c3726.png)

**Comment by Gwyrdain** [comment]
Ok, redirects should all so properly add/delete/edit then return to <b>this</b> room.

**Comment by tyn-** [comment]
I haven't started working on resets, but already the "walk through" view, and the ability to edit room descriptions from this view, as well as being able to step forward by vnum has been super handy.

**Comment by Gwyrdain** [comment]
Further improvements are possible, but for now I believe the final piece is now in place to close this issue -- being able to create a mob/mob + add the reset from room view.  The process is this:

Just like in exit editing/creation where you can create a room on the fily you can now create a mob/obj on the fly using the "New Object" / "New Mobile" selection in the reset add area.

![image](https://cloud.githubusercontent.com/assets/7820937/6433893/e2a43b64-c037-11e4-8db4-ec982cfe8470.png)

The associated mob or obj will then appear in the room view with the default garbage long desc...
![image](https://cloud.githubusercontent.com/assets/7820937/6433911/3589171e-c038-11e4-9732-13269da74661.png)

Which you can select using the normal process to jump into editing -- for object click on the long desc, for mobile click long desc to activate "look view" then click the short description at "is in perfect health."
![image](https://cloud.githubusercontent.com/assets/7820937/6433917/5671282c-c038-11e4-87bb-cbeeb1c9cd14.png)
