### ISSUE TITLE
Area flag problem

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#35]
I noticed in the formatted #AREA header, the flag line:

Flags NOVNUM NO SAVE End

NO SAVE should be NOSAVE .

**Comment by Gwyrdain** [comment]
Oh good grief.  
<pre>You tell Tynian (in common), ''NO SAVE' area flag with space goes in Format 2'.
You tell Tynian (in common), '?'.
Tynian tells you, 'Yes indeed'.</pre>
<h1>:P</h1>

**Comment by tyn-** [comment]
Apologies.  I'm not sure what question I thought I was answering.

Anyway, sorry.  No spaces for flag names.  One word per flag.

**Comment by Gwyrdain** [comment]
On the other hand finding that quote took longer than fixing it...

Done!

**Comment by Gwyrdain** [comment]
I never ask cryptic questions...

**Comment by tyn-** [comment]
Yeah,  I can't believe you looked up the quote.  :P
