### ISSUE TITLE
Area Review: Disallow duplicate resets to the same slot

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#36]
If one has already created a reset for an object worn on any of the slots that aren't multiple (ie, neck / wrist), disallow another reset to that slot.

**Comment by Cordir** [comment]
![image](https://cloud.githubusercontent.com/assets/10890489/6315348/bde028de-b9c4-11e4-8aa2-3912f7d5ab14.png)

**Comment by Gwyrdain** [comment]
done.  past transgressions not checked, but future ones are precluded.
