### ISSUE TITLE
Area Header: Area Type

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#37]
"Natural" is missing as an area wide flag.
http://wiki.tfcmud.com/index.php/Area_Flags
AREA IS NATURAL	0 (DEFAULT)

Also, changing the name of that section, from "Flags" to "Area Flags" would be nice :)

![image](https://cloud.githubusercontent.com/assets/10890489/6315501/aa370c08-b9c9-11e4-91b0-0caf6b966dfe.png)

**Comment by Gwyrdain** [comment]
Natural is actually <b>the absence of other flags</b> (i.e., when area_flags = 0).

You cannot set or unset 0 -- it's only 0 or 0 (rather than 0 vs 1 for manmade).  It cannot be combined with other flags since 0 (natural set) + 1 (manmade set) = 1 the same as 0 (natural not set) + 1 (manmade set) = 1.  No distinction.

From a user point of view I suppose we could have a checkbox for nautral than when selected disables everything else...?  Or suggest whatever is most logical to a user.

**Comment by Gwyrdain** [comment]
I don't know why Sirak optioned it like that.  The math just doesn't work... or else the area flags documentation is wrong.  Need Tynian to pipe up here.

**Comment by Cordir** [comment]
From this user perspective, having something to select/check would be helpful, even if it's a null value.

**Comment by Gwyrdain** [comment]
Done.  (It does "feel" weird because, for example, you would have to un-check natural in order to check no_vnum, but that's what we're up against as far as I can tell.)

**Comment by tyn-** [comment]
if I remember right, the only flags that are mutually exclusive are natural and manmade (and perhaps also city). If one is checked, the other should be cleared.  Default is natural.

The option itself is a no op, but it might make people feel better.

OTOH, I'd also be fine with telling people that an area is considered natural unless it is man made.

**Comment by Gwyrdain** [comment]
Need to change it back then. Would be best to reword wiki since the layman isn't thinking in terms of bitwise flags... maybe annotate that lack of manmade is natural rather than implying it as a discrete flag?

**Comment by tyn-** [comment]
Go ahead,  if you don't mind.

**Comment by Gwyrdain** [comment]
I am flip flopping a little bit and settled on what I hope is more of a happy medium.  Becuase it's either natural or manmade (or at least that is the decision that should be in the mind of the author) I made it a separate line and did as a radio button.  If anyone has a better name for than line than "environment flag" let me know.
![image](https://cloud.githubusercontent.com/assets/7820937/6316446/f792853a-b9e3-11e4-8adf-9195399a9af4.png)
