### ISSUE TITLE
Area Header: Dates Fields

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#38]
It might be nice for the ACs to have the fields in place for Install and Revision and Updated.
(Would also be handy for building Area2 headers for prior zones, which is what I'm doing)

**Comment by Gwyrdain** [comment]
The revision and updated blocks that actually go into the header are automatically controlled as I understand it and from an .are perspective must always be $revision$ and $update$.

We can add fields with these names for reference or convenience?

Installed on does need to be added and isn't in the area header right now.

**Comment by Gwyrdain** [comment]
Some form of version control is also requested under Issue https://github.com/Gwyrdain/apprentices-workshop/issues/21

**Comment by Gwyrdain** [comment]
An 'installed date' field has been provided with date picker.  If non-blank it will populate in the format 2 area header.

Closing this issue -- will let version control remain in issue 21 as noted above.
