### ISSUE TITLE
Reciprocal Exit Creation (with two existing rooms)

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#40]
I think two things are fundamentally needed here:
1.  From a room page you want to be able to create a reciprocal link -- in a specific direction -- to a pre-existing room.
2.  From the exit edit page you want to be able to <b>force</b> the far side of the exit to <b>match</b> this side when an update is made.

**Comment by Cordir** [comment]
Yes. :)

**Comment by Gwyrdain** [comment]
Interim fix for this issue:  If all room vnums are used, the "exit map" add exit button will instead start an exit in that direction from which you can select the destination, etc.  (No reciprocal update action yet.)

**Comment by Cordir** [comment]
Not sure if it's related to what you're doing, but I just got an error when creating the second half of an exit, in the Maze, from room 28 to 18, that was a door, pick/passable, Locked.

![image](https://cloud.githubusercontent.com/assets/10890489/6317179/bf3e3116-ba0b-11e4-869b-f24af54e3212.png)

**Comment by Gwyrdain** [comment]
The last thing you did was 'Create exit' or 'Update exit'?  Odd -- nothing is supposed to redirect to a room's exit index since we only like to view the exits from the room page.

Anyway, I found the error on that page and it seems unrelated to this thread and should be fixed.

**Comment by Cordir** [comment]
I just now had this happen again, in the exact same circumstance. I had already created one side of the exit, then went to that room to create the other side, clicked 'create exit' and whammo, got the error.

**Comment by Gwyrdain** [comment]
Similar url?  ends in /exits?

**Comment by Cordir** [comment]
![image](https://cloud.githubusercontent.com/assets/10890489/6317294/cb55f6b4-ba10-11e4-9bbe-9b34921c9fa4.png)
https://apprentices-workshop.herokuapp.com/areas/8/rooms/253/exits

**Comment by Gwyrdain** [comment]
When forcing reciprocal to match, I think description is excluded from the matched properties?

**Comment by Gwyrdain** [comment]
description will be excluded except when a reciprocal is newly created.

**Comment by Gwyrdain** [comment]
Item 2 should now work.  When editing an exit you can for the exit to have a matching/reciprocal exit...
![image](https://cloud.githubusercontent.com/assets/7820937/6317751/015447f8-ba24-11e4-8755-339d9c856be3.png)

**Comment by Gwyrdain** [comment]
I am actually happy with the way this method is working for now (even though it's "two" clicks instead of "one")
