### ISSUE TITLE
Area Room Defaults after creation

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#41]
I created a zone, setting a few area room defaults. Then, after creating all my rooms, I decided on an additional zone-wide room default flag (NO TRANS). I edited the zone, added the default room flag, and clicked Update. I went to the one room I did NOT want to have this default flag, so I could delete it, but it wasn't there. I checked other rooms, and the added flag wasn't on them either.

**Comment by Gwyrdain** [comment]
Yes, that would be default flags upon room creation.  A re-force all will have to be something else...  Apply flag to all, or some such.

**Comment by Gwyrdain** [comment]
Resolved -- see issue #56 for details and further work in this vein.
