### ISSUE TITLE
Disposition of "Formatted Blocks"

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#42]
![image](https://cloud.githubusercontent.com/assets/7820937/6319072/c506e366-ba6c-11e4-9cf7-81a78a689eef.png)
The formatted blocks that appear at the bottom of various pages were originally intended as a quick reference for checking whether the area file output text associated with an element was correct.  As such I think they are superfluous for day-to-day use, but may still be useful in testing for some time to come.  So the proposal is, add an area misc. setting for 'show formatted blocks' defaulted to off.

**Comment by tyn-** [comment]
Concur.

**Comment by Cordir** [comment]
<clicks like button>

**Comment by Cordir** [comment]
Agreed!

**Comment by Gwyrdain** [comment]
I guess I forgot to mention that this was done.  It defaults to off so you can turn it on if needed.
