### ISSUE TITLE
Date Field Wierdness

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#45]
So I was trying to build Area2 headers for my past zones. For Dessert Island, the creation date was some time in 1997. The mud wants the date in a specific format (MM-DD-YYYY). When I tried typing in 00-00-1997 (as the exact date is unknown), it kept reverting to 6-06-20. 

Additionally, when I use the calendar, and try to go past 2000, I get this:

![image](https://cloud.githubusercontent.com/assets/10890489/6335042/3b9213c4-bb5e-11e4-8d77-9657772e9436.png)

**Comment by Gwyrdain** [comment]
Tynian's specification for Format 2 area headers is calling for the ISO date format YYYY-MM-DD.

As to the calendar itself, mine is navigating back to 1997, so that's a little weird.
![image](https://cloud.githubusercontent.com/assets/7820937/6335104/552d4202-bb56-11e4-9c35-996adcde158d.png)

**Comment by Gwyrdain** [comment]
Oh I see, then you did that "backwards" date it thinks you are on year 6AD... so when you navigate down in years you go past year 0 into the negatives.  It seems to be remembering that 6AD date even when you clear, click out, and back in.

If you just click in before typing a date is should start up around todayish.  Also you can just input 1997-01-01.  1997-00-00 won't work.

**Comment by Cordir** [comment]
so... uh... a wetware issue. *blush*
Mybad.

**Comment by Gwyrdain** [comment]
Yes and no.  Thanks to your experience, I added the placeholder letters as a forewarning that ISO date format is desired:
![image](https://cloud.githubusercontent.com/assets/7820937/6335404/91a8743e-bb58-11e4-8c14-f78a1d7bd9ce.png)
and turned on the "Today" button in case you get lost in time and need to travel back to the present:
![image](https://cloud.githubusercontent.com/assets/7820937/6335417/a9660bea-bb58-11e4-8497-3d55c62746fd.png)
