### ISSUE TITLE
In Resets... (need to Copy a Reset with associated sub-elements)

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#47]
![image](https://cloud.githubusercontent.com/assets/7820937/6341750/78a2d154-bb8b-11e4-949d-85cc5ef5a4a1.png)

**Comment by Cordir** [comment]
(I'm trying to think of all the things that I do in Notepad, separate from SM.)

**Comment by Gwyrdain** [comment]
Resets now have "Copy" which makes a single copy of the reset (from the index page -- ok?) along with all associated sub-resets (equip/give/put for now):
![image](https://cloud.githubusercontent.com/assets/7820937/6342687/d8baca02-bb99-11e4-90e0-f63ef10f852b.png)
