### ISSUE TITLE
Unable to edit exits

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#48]
I am evidently unable to edit room exits (either one way or reciprocal).  I can configure the settings, but update fails to, well, update.

**Comment by tyn-** [comment]
The exit I was attempting to edit was a "look only" exit.  Updates weren't being accepted.

I deleted the exit, and attempted to re-create.  It created a reciprocal exit to a new room.  I attempted to edit that exit, but the update wouldn't save, either.

**Comment by Gwyrdain** [comment]
Try now.

**Comment by tyn-** [comment]
Failed.

**Comment by Gwyrdain** [comment]
I was able to duplicate the problem, but now it's fixed for me.  Can you walk be through your steps?

**Comment by tyn-** [comment]
I've been working with it a bit more.  Different behavior now.

If I edit exit, and I do NOT select force reciprocal exit, I get a reciprocal exit, but it edits okay.  If I check the reciprocal exit option, nothing happens.

**Comment by tyn-** [comment]
Ugh - maybe - I don't know where I left off on the map.  It's possible I had already linked one side of the exit...

**Comment by Gwyrdain** [comment]
Ah.  That is probably because I got so focused on forcing reciprocality I forgot to have it actually update _this_ exit...

**Comment by tyn-** [comment]
I'll get better info for you.  I need to re-orient myself with this area.

**Comment by Gwyrdain** [comment]
Corrected the problem I noted above about updating this exit.  Let me know if it's still behaving oddly.

**Comment by tyn-** [comment]
I think it is now fixed.  I'll open issue with new information if I have further problems.

**Comment by tyn-** [comment]
Thanks for the quick response - I figured I'd have to wait. :)
