### ISSUE TITLE
New exit creates room

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#49]
When I create an exit, it automatically creates a new room.  In my case, I have already created all my rooms.  I just need to connect them.

Is the auto-new-room a bug or a feature?  My preference would be to have an option to add a room, but otherwise, link to an existing room.

**Comment by Gwyrdain** [comment]
Right now clicking on the "Add Exit?" in the "Exit Map" region defaults to adding a reciprocal exit to a new room unless you already have reached your room limit, in which case it takes you to the make a new exit page.  From the make a new exit page you can link to an existing room and choose to force reciprocality if that is your wish.
![image](https://cloud.githubusercontent.com/assets/7820937/6364384/3aafceba-bc62-11e4-9609-137d94af1b49.png)

If you haven't created all rooms and want to add an exit to an existing room, the process ATM would be to use the new exit button in the exits table below, then link to and force reciprocality if desired.
![image](https://cloud.githubusercontent.com/assets/7820937/6364423/b538cca4-bc62-11e4-98a4-f9693c4b70d9.png)

**Comment by Gwyrdain** [comment]
So feature in the sense that it's the intended behavior, but... subject to suggestion and refinement.

**Comment by tyn-** [comment]
Okay, understood.

For me, I like being able to click on the exit map, as it visually matches up with my map.

Is it possible within the exit edit screen to select a "new room" option, either at the top and/or bottom of the room drop down list?

**Comment by Gwyrdain** [comment]
So long as you have vnums available you should now see this option now.
![image](https://cloud.githubusercontent.com/assets/7820937/6365138/355b1aac-bc6f-11e4-8fcd-ba60d89f13e1.png)
I tested what I could think of but there's a bit to this change, so WATCH OUT.  Also, this framework should help elsewhere... e.g., create mobs/objs one the fly in rooms.
