### ISSUE TITLE
Another easy one! - For exit map, include room number and description

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#51]
Where it says "You are here," perhaps also include room number and description.

**Comment by Gwyrdain** [comment]
![image](https://cloud.githubusercontent.com/assets/7820937/6365261/4b151904-bc71-11e4-8e7f-b07adc349788.png)

Done, though I'm not overly happy with exit map and the very limited truncation of rm names, but it's ok for now.

**Comment by Cordir** [comment]
You "AREA" here? Nice pun. :D

**Comment by Gwyrdain** [comment]
er...

**Comment by Gwyrdain** [comment]
fixed.

**Comment by tyn-** [comment]
Yep, the truncation is not ideal, and maybe the boxes could be a little bigger without too much of a sacrifice of space... but it's still enough to give a hint on the room.
