### ISSUE TITLE
Line wrap for room descriptions?

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#52]
The ruler is handy - but how would you feel about auto-linewrap for room descriptions?

**Comment by Gwyrdain** [comment]
It already does that.  Just don't do your own linefeeds and it will wordwrap for you (currently at 75).  The wordwrap occurs on output (since the 75 bit can change or your content can change).

**Comment by tyn-** [comment]
Dang it.  I've been doing those myself.

Okay!

**Comment by Gwyrdain** [comment]
Also, if you lets AW manage your wordwrap, the on-the-fly wrapping and truncanting in the index view will work...
![image](https://cloud.githubusercontent.com/assets/7820937/6365234/dfa69260-bc70-11e4-8e16-619a8597d74b.png)

If you're insistent on being a linefeed megalomaniac you have to live with this:
![image](https://cloud.githubusercontent.com/assets/7820937/6365246/2587fbfc-bc71-11e4-824e-d72705ac0aac.png)

**Comment by Cordir** [comment]
I resemble that remark. :)
