### ISSUE TITLE
Edit/Delete Multiple Targets at Same Time (ROOMS/OBJS/MOBS) - OR defaults for MOBS/OBJS

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#56]
It would be handy to have the ability to edit multiple rooms/objs/mobs at the same time, especially certain fields that might be common among a group of "targets."

An example may clarify.  For my quest, I'll need some number of mobs (some/all) with certain common special functions.  For quests, teleport_on_load is popular.  I may want for some or all mobs not to hunt (spec_no_hunt), or auto-respawn on death (spec_respawn).

It would be a time saver if I could do all of that at one time.

Object/mob/room flags might be another area where being able to set multiple targets at once might be handy.  For rooms, at least, you can select default room flags, so that lessens the pressure for those flags.

As an alternative, if we could set default values for those various types, that would work, too..., as least for targets made after the default is set.

**Comment by Gwyrdain** [comment]
Understood, but this likely cannot be done in time for this quest.

Also, per wiki, "Of the specfun class called Specials, only one special per mob is allowed."  I was unclear as to whether that was a "guideline" allowed or a coded allowed...  From the above I assume it is the former.  Currently I am precluding > 1 but its at the UI level not structural, so we can open it to unlimited and just to area review warnings when > 1 is used?  (Same prohibition is in place for rspecs and triggers now.)

**Comment by tyn-** [comment]
I wasn't expecting you to make changes based on my timeline.  It was only an example.

A long time ago, a mob only accommodated one special function.  That technical limitation no longer exists.

According to the wiki, the use of any special function is subject to AC approval prior to use (ref. http://wiki.tfcmud.com/index.php/Area_Special_Functions).

Does this accurately reflect your preference, Tokugawa?

**Comment by tyn-** [comment]
I would allow multiple special functions, but warn if there is more than 1, as that can be a "gotcha."

**Comment by Gwyrdain** [comment]
<h3>WGPCGR</h3>
Multi-room editing is now available.

![image](https://cloud.githubusercontent.com/assets/7820937/6428417/7dbb690e-bf5e-11e4-9542-985b3c05c0a3.png)

Blank fields are NOT updated.  As such check boxes are replaced with selections that allow blank, set or unset:
![image](https://cloud.githubusercontent.com/assets/7820937/6428449/827daa5a-bf5f-11e4-86a4-3317b3134aa8.png)

**Comment by Gwyrdain** [comment]
Multi-edit for objects and mobiles is now available as well, with a couple exceptions.  For objects I'm not allowing the type specific values (v0-v3) to be set through multi-edit.  The second exception is that associated (i.e., subordinate) records are not updated through this process, which are given below in case it wasn't already obvious:
* For rooms:  exits (and their subordinate triggers), extra descriptions, rspecs
* For mobiles: special functions, shopkeeper assignment
* For objects:  applies, extra descriptions

I understand from the above that multi-assignment (and dis-assignment?) of mob/specials are desirable, though I think this can be limited to normal specials and extended specials can remain a one-by-one thing.  Maybe room specials too, but I perceive limited utility here and am leaning towards no.  Same for the others.  Please comment if you disagree or have further insight.

**Comment by Gwyrdain** [comment]
Ok, add/remove _normal_ mob special is available via the multi-edit mob form.
![image](https://cloud.githubusercontent.com/assets/7820937/6433489/cae3663a-c02d-11e4-8b70-2c405b857af4.png)
At this time, I am going to consider this issue resolved.  Please discuss further as desired and create to issues for specific adds.
