### ISSUE TITLE
Ability to add GIVE/EQUIP reset in mob edit view?

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#58]
I am adding mobs to rooms (resets) from within the room view.  I sometimes need to give items to those mobs.  I'd like an easy way to do this.  One idea is to give ability to set a GIVE/EQUIP reset within the mob edit view.

**Comment by Gwyrdain** [comment]
Probably mob reset view, not mob edit view?  G/E are assigned per reset rather than per mob since mobs may have different resets some of which want G/E and some of which may not?  (At least in hypothetically.)

**Comment by tyn-** [comment]
Good point on mob edit view.

I'd like a way to deal with equipping mobs "close" to the walk-through/room view.  I'm not sure of the best way to accomplish that.

**Comment by Gwyrdain** [comment]
understood and agreed.  In walk through view you should be able to (somehow) effectively look at a mobile (though without a console) see their inventory/eq and/or add to it.  Could be in the normal room view pane (though this would get busy fast( or in a separate pane, or other suggestions?

**Comment by Gwyrdain** [comment]
Note to self, this is what a look looks like, e.g.:
![image](https://cloud.githubusercontent.com/assets/7820937/6407980/acd35d66-be08-11e4-98de-2b2422860a01.png)

**Comment by Gwyrdain** [comment]
This is WIP, but warning cause it just change on live app.  clicking on mobs "looks" at them instead of edits them now.  Shows E/G resets therein. with edit obj/edit reset/delete reset links.  Just no add E/G yet.  
![image](https://cloud.githubusercontent.com/assets/7820937/6422721/0942dbc2-be99-11e4-9e89-d334664fd495.png)

**Comment by Gwyrdain** [comment]
additional controls in now.  add, revmove
![image](https://cloud.githubusercontent.com/assets/7820937/6424838/fe208e46-bec6-11e4-8fc3-134642887ac3.png)

**Comment by tyn-** [comment]
Nice idea, but it's also nice to have ability to edit mob in walk through mode.  Can you add 'edit' to the give | equip line?

**Comment by Gwyrdain** [comment]
the edit mobile link is on the in perfect health line. it was probably too subtle.

**Comment by tyn-** [comment]
Aha! Okay.
