### ISSUE TITLE
Area output problem

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#61]
Quotes, ampersands, and possibly other characters are not exporting as plain ASCII characters.  

Example: 

the â€œLongest inaugural address &amp; shortest tenureâ€^Ý award~

Was supposed to be:

.... Aha, this was my fault for copying and pasting from Word document.  Editor will gladly accept these characters.  I'm not sure if this is something you can do anything about, but it is a potential "gotcha."

**Comment by Gwyrdain** [comment]
I've also copy pasted in non-standard characters -- e.g., characters with accent marks.  It might be possible to translate/substitute for standardized, but in the end it would probably be better to just disallow everything but the "approved characters list."  Is there any chance you can tell me what this is definitively?

**Comment by tyn-** [comment]
Not really.  I'd say ASCII.

A bigger problem is the &.  It gets included as &amp; .

**Comment by Gwyrdain** [comment]
I don't follow "& is encoded as &."  What am I missing?

**Comment by Gwyrdain** [comment]
nevermind, I see it.

**Comment by Gwyrdain** [comment]
done. the input bit will have to be dealt with separately.

**Comment by Gwyrdain** [comment]
As for the input problem all text fields (AFAIK) are now validated against the printable ASCII chars using the regex [ -~].  Probably tilde should be excluded -- anything else?

**Comment by Cordir** [comment]
I wrote a mob today, using only standard characters, but got the 'you used something non-ascii' error. screenshot below. :(

![image](https://cloud.githubusercontent.com/assets/10890489/6698197/ac79f2e2-ccc4-11e4-9079-4bda42eaf4b7.png)

**Comment by Cordir** [comment]
(I deleted the description and was able to continue.)

**Comment by Cordir** [comment]
Another example from today:
![image](https://cloud.githubusercontent.com/assets/10890489/6742298/98c6358c-ce5c-11e4-916b-adf0170ce550.png)

**Comment by Cordir** [comment]
I thought maybe the spaces were behaving weird, since it was a cut/paste, so I retyped the whole thing manually. Still got the error.

**Comment by Gwyrdain** [comment]
I am unable to duplicate this problem.  Can you copy/paste the above into a plain text file, then copy paste into AW to verify it still doesn't work for you, then send me the txt file?

**Comment by Cordir** [comment]
I retyped the whole thing from scratch in Notepad, and attempted to paste it into AW. I got the same error. I have emailed you the text file.

**Comment by Gwyrdain** [comment]
Er, oops.  The pattern [ -~] didn't include LF/CR's.  How silly.  Now allowed for multi-line text.  Problem should be resolved.
