### ISSUE TITLE
Last Edit By / Date

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#62]
Having a field that shows the date of the last edit of an area, and by whom, in the My Areas summary, would be Nifty and Handy.

**Comment by Gwyrdain** [comment]
Last edit date/time shown in the area table.  By whom is more problematic.

**Comment by Gwyrdain** [comment]
Last update too cumbersome.  Update area field on various save/destroy controller actions (with current_user).
Maybe https://github.com/chaps-io/public_activity, but TMI?

**Comment by Gwyrdain** [comment]
Going forward lasted update time and by whom will be shown.  Until the next edit is made, the user will show Unknown.
