### ISSUE TITLE
Spec_one_Spell

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#64]
When one selects Spec_one_spell, one must then designate what the spell is. This should NOT be a blank text field, but rather a spell selected from the spells.lst

**Comment by Cordir** [comment]
(Delete this. I didn't see that you have to go back to the screen, then back into edit, to get the spell field.)

**Comment by Gwyrdain** [comment]
This field differs from the others in that it uses a spell name rather than number.  There is no specific list given.  Should the same list from spell numbers be used?  Are they all exactly correct, except maybe lower case?

http://wiki.tfcmud.com/index.php/Spell_Numbers

**Comment by Cordir** [comment]
It should have the exact same list from spell numbers, yes.

**Comment by Gwyrdain** [comment]
selected by list now
