### ISSUE TITLE
possible broken link in tooltip on exit creation page.

### ISSUE THREAD

**Issue by TFCGhaz** [Gwyrdain/apprentices-workshop#66]
Discovered this while looking for something else, thought I should mention it in case you weren't aware.
![apprenticesworkshoptooltiperror](https://cloud.githubusercontent.com/assets/11604800/6772552/ffa26eb2-d0f8-11e4-9ecf-75a69aa8d858.png)

**Comment by Gwyrdain** [comment]
Yes, I see.  The link itself is good but the generated link "title" is goofed.

**Comment by TFCGhaz** [comment]
yeah, after posting the issue I thought about it and realised that it was just what was supposed to be seen that was b0rked :+1:

**Comment by Gwyrdain** [comment]
Fixed
