### ISSUE TITLE
Doors with keys not set correctly

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#68]
This may already be fixed.  I didn't have a chance to investigate when I did my quest area, but I edited the area file last night to try to determine why the doors and locks did not work.  This covers the doors issue.

What I found on doors with keys was this:

#18459
Detention Cell~
You are in a detention cell.  The way out is through a downward staircase.
~
D5
~
~
2 **139** 18442

The interesting number was '139'.  I think that's probably an internal reference to the specified key object that did not get "translated" to vnum when exported.

**Comment by Gwyrdain** [comment]
Yes, looks like that was missed.  Added formal vnum translation and handling for external vnums.

Also, noticed and corrected behavior where edit form was defaulting to no key even when a key was previously defined.
