### ISSUE TITLE
Description Only US-ASCII characters are permitted.

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#72]
It would be _AWESOME_ if it would tell us what non-ascii characters are in use. I get a lot of content that's built in MS Word, and figuring out which one character is non-ascii is challenging sometimes.

**Comment by Gwyrdain** [comment]
All invalid characters will now be displayed in the order found.  Example below.

![image](https://cloud.githubusercontent.com/assets/7820937/14407329/5f7e6a3a-fe79-11e5-8d30-91737d3e2df2.png)

**Comment by Cordir** [comment]
I had a mob that I wrote several months ago. I edited the mob today, to increase its level. _I did not change its description._ When I saved the mob, I got the error that there were ascii characters that would not save, but none were listed.

![image](https://cloud.githubusercontent.com/assets/10890489/14432188/a38d59b0-ffce-11e5-96f4-884aadc9e914.png)

**Comment by Cordir** [comment]
I tried making a brand new object, typed entirely in the AW, with no pasting, and got the same message:

![image](https://cloud.githubusercontent.com/assets/10890489/14432538/3af4c2f6-ffd0-11e5-80f1-36ebbab878ad.png)

**Comment by Gwyrdain** [comment]
It's probably the line feeds.

**Comment by Gwyrdain** [comment]
Updated and fixed.  Please confirm.

**Comment by Cordir** [comment]
Appears to be fixed, thank you!

![image](https://cloud.githubusercontent.com/assets/10890489/14447746/21ac7160-0028-11e6-8637-c68c6f87d58c.png)

**Comment by Cordir** [comment]
and I did a non-ascii and it showed up in the alert beautifully:
![image](https://cloud.githubusercontent.com/assets/10890489/14447760/56d8b68c-0028-11e6-9fbe-e49aaf1e2cc1.png)

**Comment by Cordir** [comment]
Got this today:
![image](https://cloud.githubusercontent.com/assets/10890489/15585351/752743bc-2344-11e6-90a7-a66042e7cd2a.png)

Something is bugging it, but it isn't able to discern what... :(

**Comment by Gwyrdain** [comment]
Copy/paste the entry into a plain text file and email, please?

**Comment by Cordir** [comment]
Erm. I retyped the entire text into Notepad and pasted it in, and it worked.. I don't have the 'bad text' any more :(
