### ISSUE TITLE
Exit Issues

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#73]
So, I've created an entire zone in the Workshop - The Boneyard.  There is _something_ going on with Exits, and I'm not sure what. The exit shows up in the Workshop. It shows up in the exported area file. It does NOT exist on the mud. And I don't mean one or two are missing on the test port: Fifty six are just... not there.  I have no clue why. I don't know if it's a mud thing, or its a Workshop thing, or what it is.  I'm cross posting this here, in the area forum for the zone, and to the God+ area of the forum so Tyn will see it.

For example:

#32710
On a Path in the Boneyard~
Protected from the wind by the bordering wall that lies to the west, the
grass here is particularly long and verdant - nearly waist-high. It brushes
against your clothing, making an eerie sighing sound that might be found
disturbing by less bold individuals. The pathway leads to the north,
towards the exit, to the south, deeper into the graveyard, and to the east,
along a row of sad, ill-maintained mausoleums. The well-picked carcass of
an unusually large raven lays in the midst of the path just a few steps
away, a grisly reminder that many of the creatures found here have unending
hunger.
~
327 1048576 2 
D0
~
~
0 0 32775
D2
~
~
0 0 32785
D3
~
~
0 0 32744
S

live on mud, only the west exit shows up. North and south are missing.  (The _majority_ of the missing exits are north or south.  IN two sections, ALL the exits are missing.  I'm wondering if it has to do with the reciprocity? 

I'm going to try to delete the exits and re-create them, and see if that helps.

**Comment by Gwyrdain** [comment]
Resolved?

**Comment by Cordir** [comment]
Resolved! It turns out it was a code issue.  From my area forum?

ME: So, I realized staring at the map last night that it is every exit linked to a room above a specific vnum: 32768. I don't know if that's some sort of bizarre, magical number in the mud code, maybe? (Tyn - do you know if there's anything code wise that could cause the issue?)


TYNIAN:  Why yes, I believe there is a code issue. 32768 is 2^15 power, which I believe is the size limit for a short integer. I did this way back in the beginning when I was trying to be memory efficient as possible. I had since expanded these to a full integer... but I missed the exit data structure, which still uses short int.  Good spotting. I'll fix it.

So this is totally a TFC thing (Fixed!)  and NOT an Apprentice's Workshop thing.
