### ISSUE TITLE
Objects with no long description

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#78]
There are times that one wants to create a hidden thing - generally a container - that has a keyword, and a short description, but no long description. Maybe if there was some sort of secondary validation that one really DID mean to leave that blank, could this be allowed?

**Comment by Gwyrdain** [comment]
Suggest:  Allow long description to be blank.  Add a warning in area review for such instances.

**Comment by TokugawaTFC** [comment]
That works for me.

**Comment by Gwyrdain** [comment]
Updated to allow 0 length long desc + added warning:

![image](https://cloud.githubusercontent.com/assets/7820937/14482379/f579fe36-00f0-11e6-9211-4edb233bd13d.png)
