### ISSUE TITLE
Dependent Resets (Display Toggle)

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#82]
Would it be possible to have a toggle in the Area setup that allows you to toggle whether or not Dependent Resets are hidden or displayed? The default is Hidden - you have to individually select to see them, and I prefer to see them all, always.

**Comment by Gwyrdain** [comment]
User selectable setting (see 'edit profile'). profile').  By default they will not be collapsed.

![image](https://cloud.githubusercontent.com/assets/7820937/14618430/69de72be-0567-11e6-9489-64253c23c777.png)

Related items:  I think that "Use Rulers" should probably migrate to a user setting, but show formatted blocks should remain an area setting (given that these take processing time, I can see these being more useful for testing on smaller areas, and less useful on real areas grow that become quite large).

**Comment by Gwyrdain** [comment]
"USE RULERS" was moved to a user setting and will default to OFF.  You will need to turn on in your profile to re-enable.

**Comment by Gwyrdain** [comment]
Also, user's "Profile" and "Settings" were broken up because I was annoyed at inputting a password just to toggle these options.

![image](https://cloud.githubusercontent.com/assets/7820937/14628083/76afad30-05af-11e6-9e63-19c64f467e28.png)
