### ISSUE TITLE
Something about a room causes a display issue?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#84]
The first room (but not other rooms) in one of the zones I'm working on is displaying like this:

![image](https://cloud.githubusercontent.com/assets/10890489/14677564/c889379c-06d7-11e6-880d-c800332f262b.png)

This has happened in the past; I just work on a different room for a bit and go back to the weird looking one, and it stops, but it's been like that twice today, so I figured I'd mention it.

**Comment by Cordir** [comment]
Found another room doing it. Here's a snippet of what the map section looks like, display-wise:

![image](https://cloud.githubusercontent.com/assets/10890489/14678543/c8342c8a-06db-11e6-910b-25a97715c928.png)

**Comment by Gwyrdain** [comment]
Wasn't properly dealing with no_equip mobiles.  Should be fixed now.  Both issues stemmed from the same lack of a closing /div.
