### ISSUE TITLE
Long Description Ruler

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#87]
With the new nifty 'checking line length' thingy, i now know that a gazillion of my objects have a long description that is too long. Could we add a ruler to the object creation page so folks know when they've gotten close/ gone over the length limit for the long description, prior to checking the zone for issues?

**Comment by Cordir** [comment]
er, ignore this.

**Comment by Cordir** [comment]
Actually, yeah, it is missing. i got myself all confused. a ruler for objects would be nifty.

**Comment by Gwyrdain** [comment]
added ruler at obj ldesc.
