### ISSUE TITLE
Add Resets to the button array?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#88]
![image](https://cloud.githubusercontent.com/assets/10890489/14723219/8e32f0d4-07d5-11e6-8569-2b5bf12ac90f.png)

Can we add Resets to these nifty buttons?

**Comment by Gwyrdain** [comment]
Done.

**Comment by Cordir** [comment]
It now appears on the main sections of Objects / Rooms / Mobs - thank you for adding it! - but is not included on the individual pages for any category, FYI.

**Comment by Gwyrdain** [comment]
I don't follow.  E.g., For each object page they are to the left of the last/next buttons?

![image](https://cloud.githubusercontent.com/assets/7820937/14756459/54a50ca2-089e-11e6-8eea-4fba7368b325.png)

**Comment by Cordir** [comment]
I"m thinking maybe it was a browser cache issue. It's showing up everywhere at home, but wasn't at work, which tends to cling to its cache more.

**Comment by Gwyrdain** [comment]
Adjusted the panel headers further to eliminate goofiness with long names and breakes next/prev onto separate line (where appropriate).

![image](https://cloud.githubusercontent.com/assets/7820937/14759549/0c2fcb2c-08dc-11e6-97b9-b6ba79389887.png)
