### ISSUE TITLE
Alert for overloaded container:

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#89]
![image](https://cloud.githubusercontent.com/assets/10890489/14723929/0708254e-07d9-11e6-92eb-20baaa687b66.png)

I have a container that weighs 800, and has a carry capacity of 50. (see above) Inside it are four objects, each which weigh one.  One of the four objects contains 6 objects that weigh 0.   I'm getting an error that the container is overloaded, but I'm having a hard time understanding why. The total combined weight of the objects inside is 4, out of the available 50.  

![image](https://cloud.githubusercontent.com/assets/10890489/14723375/6041384c-07d6-11e6-9195-0da1d938d829.png)

in sirak's muditor, there was weight and maximum weight.  Per Tokugawa:

" Weight refers to how much the container itself weighs and maximum weight refers to the weight of the container + how much container will hold. 
So....
Weight of 5
and Maximum weight of 35
The container weight is 5 and will hold 30." 

Am I reading the field labels incorrectly in AW? If so, could we put in some sort of clarifying notes/something to make this clearer?  Or is the AW incorrectly calculating the overload?

**Comment by Gwyrdain** [comment]
The hold weight field in the form is the Value0 obj type spec.

![image](https://cloud.githubusercontent.com/assets/7820937/14725265/ac11c6a8-07cf-11e6-8943-a1122762f159.png)

As such, based on my understanding, to achieve a capacity of 50 for something that in and of itself weights 800, you would have to enter 850 in that field.

It's certainly possible to deal with this differently, whether in terms of descriptive text or behind the scenes automation.

**Comment by Gwyrdain** [comment]
Issue #9 is currently tagged awaiting review.  This comment is a review. Closing in favor of 9.
