### ISSUE TITLE
Container weight calculations

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#9]
Please validate for container weight issues (for all resets).  Warn only?

**Comment by Cordir** [comment]
Containers are the bane of my existence.  I can never tell how to put them together. I invariably get the weight of the container mixed up with how much it can hold. Siraks' Muditor is Very Unhelpful in this regard. I have screwed up every single one I have ever made. (*does not learn quickly*) If you can make it simpler, I will praise your name from the highest rooftops. Or, uh, maybe while standing on the couch.  But the intent is there.

**Comment by Cordir** [comment]
i DID, in fact, make a container. Whether or not I did it right, remains to be seen.

**Comment by Gwyrdain** [comment]
On hold pending understanding, documenting, and implementing of the I reset.

**Comment by Cordir** [comment]
Tokugawa - this is an issue that needs your help / testing / expertise...

**Comment by Gwyrdain** [comment]
I agree and here's why...  If I could, I would mess with I resets 6 ways from sunday to see what they can and can't do, if they _must_ follow such and such or can they go wherever.  Is multi-multi-nesting possible or just two deep.  These are important questions because it affects structural issues in the "model associations".

For example, right now "Equip" and "Give" resets _belong to_ "Mob" resets and ALWAYS follow the mob reset.  Likewise "Put" resets belong to "Object" resets... but maybe put resets don't have to follow in this way since they state the item vnum of the container?

This "Insert" reset business changes things since it seems like maybe they can belong to an Object reset, an Equip reset, or a Give reset.  If so, I'm not yet sure how to work this... but again maybe they can be loosey goosey and go wherever in the reset order?  If so maybe the belongs to association isn't needed and life is easier than I am thinking.

I realize this is a tough request, but the more info the merrier.

**Comment by Cordir** [comment]
In case he doesn't see the activity.... @Tokugawa .. please look at this thread :)

**Comment by Gwyrdain** [comment]
Added container (weight) capacity calc.  Needs validation, then a warning system can be added for overloads.

![image](https://cloud.githubusercontent.com/assets/7820937/14696868/a8e1d884-0733-11e6-8c0e-efaacb260232.png)

**Comment by Gwyrdain** [comment]
Does not work for legacy puts.

**Comment by Gwyrdain** [comment]
However, a new option will appear (in resets table footer) to allow one-step conversion of legacy puts (if you had any).

**Comment by abagby** [comment]
Added overweight containers to area review.

**Comment by Cordir** [comment]
could we rename the fields?
Weight -> "Weight of Container"
Carry Weight -> "Container Weight + Carry Capacity" 

OR:

Change 'Carry Weight' to 'Total Weight' and insert a line of instruction when the object type Container is selected, that under the "Carry Weight" field, that says:
(Reminder: This value must be the weight of the object of itself plus the carry capacity.)

**Comment by Cordir** [comment]
(I kinda prefer option 2)

**Comment by Gwyrdain** [comment]
Changed the "value_0" field to be called "Weight (loaded)," meaning the fully loaded weight, and made it not user controllable.
Added a form field called "Capacity (weight)."
The "Weight (loaded)"/value_0 is calculated and updated automatically.

![image](https://cloud.githubusercontent.com/assets/7820937/14759164/039d7540-08cd-11e6-83f7-3fb6016f98db.png)

**Comment by TokugawaTFC** [comment]
How does the calculation decide how much the container should weigh? What if I wanted a container to weight 5 and hold 20? Can I do that? If not we will still need to be able to manually enter both values.

**Comment by Gwyrdain** [comment]
The object weight field was unchanged.  Both the container's intrinsic weight and its carrying capacity must be entered.  Only the value_0 is determined from summing those two.

**Comment by Cordir** [comment]
Right now, the container object layout has the three fields, but 'weight' is orphaned by itself, visually. Maybe could you scoot it up so it is with the other weight fields? Also, maybe change 'weight' to 'Weight of container' just for clarity?

![image](https://cloud.githubusercontent.com/assets/10890489/14792586/85aca9d8-0ae0-11e6-9f23-2ecc1236319f.png)

**Comment by Cordir** [comment]
Ideally:
Weight of Container
Weight Fully Loaded
Capacity (Calculated)

**Comment by Gwyrdain** [comment]
The weight loaded is the calculated one.  Additionally the weight entry is the object weight and is common to all object types.  The fields below object type are the fields specific to that type.  I understand the desire, but it also feels weird to have obj weight in different places on the form based on obj type.

**Comment by Gwyrdain** [comment]
Upon further reflection, I think the use just doesn't need to know about the container object's value_0 entry -- it should just work / KISS.  So, it's just the (hopefully) intuitive "Capacity" as a container property and "Weight" as a basic object property.
![image](https://cloud.githubusercontent.com/assets/7820937/14937701/8d9ae32a-0ec4-11e6-813d-00cc36e7cacd.png)

**Comment by Cordir** [comment]
If "Weight" is the object's weight, and "Capacity" is what it holds, and the AW is calculating the value_0, then  this doesn't appear to be working as described above.

I got an alert of an overloaded container, and had to adjust the Capacity to include the weight.

![image](https://cloud.githubusercontent.com/assets/10890489/14956709/c2a537ea-1046-11e6-90cd-1b6545857e96.png)

**Comment by Cordir** [comment]
It did not increase the value - I had to do so manually, so far as I can tell.

**Comment by Gwyrdain** [comment]
The alert was indicating that the value_0 was automatically updated; however, the capacity was not commensurately being updated.

**Comment by Cordir** [comment]
FYI, the "Legecy Resets Converter" thingy in the Resets summary footer is mispelled.

**Comment by Gwyrdain** [comment]
fixed
