### ISSUE TITLE
deleting an extra description / no navigation

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#90]
Most editing windows, once you're done editing the thing, there's the Back / Edit / Delete buttons.  If you start deleting extra descriptions on an object, it takes you to a list of all the extra descriptions for that item. You don't have the back/edit/delete buttons, or the Rooms/objects/mobiles/resets button. You don't have any. You can only navigate by selecting Areas and going back into the zone.

![image](https://cloud.githubusercontent.com/assets/10890489/14830029/34b4943a-0bb4-11e6-8d4b-8374dc85ad1f.png)

**Comment by Cordir** [comment]
( I didn't delete the object, I deleted all the extra descriptions, btw.)

**Comment by Gwyrdain** [comment]
Updated the way these redirect and the notice that was wrong.  Also extended the new header panel feel to oxdescs and applies (which still needs to be extended into other areas).
