### ISSUE TITLE
Add the ability to create a mob reset from the mob editing screen?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#91]
Sometimes I already know where a mob's going to be when I build it.  We have the ability to reset a mob or object into a room when we create the room.. could we add the ability to reset a mob, from the mob creation screen, instead of going out into resets and adding it there?

**Comment by Cordir** [comment]
Also for mob resets:
Maybe a 'Reset in multiple locations' option that would let us select all the rooms that the mob will be reset, in one fell swoop, rather than having to go back out to resets, click add, select the mob, select the room...

**Comment by Gwyrdain** [comment]
Added "associated resets" tables to obj and mobs.

Given how cumbersome the general resets table is esp on fleshed out areas, consideration should be given to moving entirely in this direction -- i.e., dealing with resets from the room, obj, mobile level. R reset is the exception, but this can also be controlled from the room level?

**Comment by Cordir** [comment]
I would prefer, if it's possible, to allow multiple ways to do the same thing: Have a resets page. Have the ability to add a mob to a room from the room page OR the mob page.

**Comment by Gwyrdain** [comment]
I also added a similar panel to rooms for the randomize reset.  I have removed the randomize resets from the main index so that they're only added/removed from the room view.
