### ISSUE TITLE
Custom Reset Comments

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#92]
Allow input of custom reset comment text.  In this way reset comments may be imported and retained.  Additionally, there may be cases when user control of comments is desired or when special care is needed (e.g., reset involves external vnums for which AW inherently does not recognize for commenting purposes).

**Comment by lpkirby** [comment]
This will be done when the pull request for #131 is merged.  

If there is already a comment on a reset, it is kept.  If there is no comment, the current automatically generated comments are used.  The UI also has a place to edit comments for all resets including "comment resets."
