### ISSUE TITLE
Add support for C & F Resets

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#94]
These resets are not documented and likely require special permission to be used; however, to provide the best functionality possible we should include support for such.  On the permission side, the AW approach would probably be similar to other permissioned elements whereas everything is "allowed" by AW but warnings are shown (in "area review" and maybe elsewhere) reminding the user and alerting AC's for validation.

**Comment by Gwyrdain** [comment]
My notes on the examples I saw (including seeming inconsistencies) are below.  Additional examples are welcome.

![image](https://cloud.githubusercontent.com/assets/7820937/14942828/22c8e7c2-0f7d-11e6-920e-cacb267e10d5.png)

**Comment by Cordir** [comment]
I know that there are zones who currently use these resets.  I know that players think of them like 'easter eggs' of a sort, and think they are awesome.  I wish that their use was allowed in the same way that Specials are allowed - in very limited quantity and with AC permission.

**Comment by tyn-** [comment]
After consulting the code:

value 1 - Not used (disregarded) for any reset.
value 2 - Type 0 - weapon, 1 - armor, 2 - potion, 3 - misc - random random, pretty much any type
value 3 - Level - No longer used.  Used to influence the power level of random item.  Now just ignored.
value 4 - Not used for 'G', 'R', 'C' or 'F' resets (set to 0).

**Comment by Gwyrdain** [comment]
Added support.  Should be able to import/export/create/edit these.  An area review warning will be shown when any of these are present.
