### ISSUE TITLE
Tried to import an area that exists on the site...

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#95]
and I received the below error. I am looking at The Boneyard and noticed the vnum range was not correct. So I wanted to import the file and then change the vnum range.

An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

**Comment by Gwyrdain** [comment]
Existing areas are not a problem.  When one exists your new one gets bumped to the next revision number.  So if the original was (Rev. 0), the new one will be (Rev. 1).

Have you tried again?  It could just be that I was pushing an update and it was re-building.

**Comment by TokugawaTFC** [comment]
It worked this time. Thanks
