### ISSUE TITLE
Mob & Object Line Length

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#97]
So seeing the mob or object with the associated flags in the creation process would be super helpful. 
Once flags are added, could they maybe show below the field for Long description, like this:

Ldesc:  Matthew Salamir rises from his unquiet rest and attacks in a rage.
(Blue Aura) (White Aura) Matthew Salamir rises from his unquiet rest and attacks in a rage.
---+----|----+----|---+----|----+----|---+----|----+----|---+----|----+----|---+----|----+----|---+----|----+----|
So folks can see, at creation, what it will look like and can correct too-long descs then and there?

**Comment by Cordir** [comment]
So right now, I'm getting an alert that my mob has a length of 81 characters. It's got a red aura, but is not sanc or invis, and if I type in the aura as a visual cue, it still looks like I should be well within the 80 character limit. 

![image](https://cloud.githubusercontent.com/assets/10890489/14958516/c570ef82-1050-11e6-8adc-695247bd3eb4.png)

**Comment by Cordir** [comment]
(So the specific example above was getting tripped up by the aura issue, which has been resolved. - But a flags thingy would be supercool.)

**Comment by Gwyrdain** [comment]
Added this for mobiles.  Please review and then we can do something similar for objects.

**Comment by Cordir** [comment]
Yay! That works! :) Very helpful.

**Comment by Gwyrdain** [comment]
On objects as well now.
