### ISSUE TITLE
system error?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#98]
I was opening a room to look at the 'mud view' to see if I could figure out why a mob was showing up as having too long of a description, and I got this message:

ActionView::MissingTemplate in Rooms#show
Showing /app/app/views/rooms/_mudroomview.html.erb where line #16 raised:

Missing partial rooms/_mudmobilepoke, application/_mudmobilepoke with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/app/app/views"
  * "/app/vendor/bundle/ruby/2.1.0/gems/devise-3.4.1/app/views"
  * "/app/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-extras-0.0.7/app/views"
Extracted source (around line #16):
13
14
15
16
17
18
          
   <font color=lightgray>></font><% if @area.resets.where(reset_type: ['M', 'Q']).where(val_4: @room.id).count > 0 %><%
   @area.resets.order(:val_2).where(reset_type: ['M', 'Q']).where(val_4: @room.id).each do |reset| %><% if Mobile.exists?(:id => reset.obj_id) %><%=
   render 'mudmobileview', :reset => reset %><%=
   render 'mudmobilepoke', :reset => reset %><% end %><% end %><% end %>
   
   <% if current_user.use_rulers? %><%= WORDWRAP_RULER %><% end %></div>

Trace of template inclusion: app/views/rooms/show.html.erb

Rails.root: /app

Application Trace | Framework Trace | Full Trace
app/views/rooms/_mudroomview.html.erb:16:in `block in _app_views_rooms__mudroomview_html_erb___1485697294286202303_70251330390920'
app/views/rooms/_mudroomview.html.erb:14:in `_app_views_rooms__mudroomview_html_erb___1485697294286202303_70251330390920'
app/views/rooms/show.html.erb:24:in `_app_views_rooms_show_html_erb__3117939002797475201_70251331535940'
Request

Parameters:

{"area_id"=>"48",
 "id"=>"2379"}
Toggle session dump

**Comment by Gwyrdain** [comment]
Should be fixed.
