### ISSUE TITLE
Add a link to edit the mob to the room view?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#99]
Since the room view helps with fixing mobs and objects, perhaps there could be a link to edit the specific mob or object? (We can add equipment resets in the room view, but not move screens to edit the mob itself)

**Comment by Gwyrdain** [comment]
For mobiles, it's here:
![image](https://cloud.githubusercontent.com/assets/7820937/14958866/a5f86b1c-1041-11e6-822e-f23dc6587d95.png)

For object's it's here (though this one is expected to change in future):
![image](https://cloud.githubusercontent.com/assets/7820937/14958890/bcb8e368-1041-11e6-8033-900d0795a452.png)
